name: xfrpc-x86_64

on:
  # Only manual trigger from Actions tab
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    
    - name: prepare build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libjson-c-dev libevent-dev libssl-dev gcc-14 g++-14

    - name: compile xfrpc
      env:
        CC: gcc-14
        CXX: g++-14
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ls -ltr

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: xfrpc-x86_64
        path: build/*
        retention-days: 7
    
